using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
/// <summary>
/// Descripción breve de Catalogos
/// </summary>
public class Catalogos
{
    public Catalogos()
    {
        //
        // TODO: Agregar aquí la lógica del constructor
        //
    }
    public static string GetErrorMAP(string CodError)
    {
        switch (CodError)
        {
            case "12":
                return "12 - No les da la gana explicar este error";
            case "13":
                return "13 - Giro retenido de agente bloqueado";
            default:
                return "6 " + CodError + ": Desconocido";
        }
    }
    public static int GetCodeEliteFromSufijo3(string Sufijo3)
    {
        switch (Sufijo3)
        {
            case "ABW":
                return 533;
            case "AFG":
                return 4;
            case "AGO":
                return 24;
            case "AIA":
                return 660;
            case "ALB":
                return 8;
            case "AND":
                return 20;
            case "ANT":
                return 530;
            case "ARE":
                return 784;
            case "ARG":
                return 32;
            case "ARM":
                return 51;
            case "ASM":
                return 16;
            case "ATA":
                return 10;
            case "ATF":
                return 260;
            case "ATG":
                return 28;
            case "AUS":
                return 36;
            case "AUT":
                return 40;
            case "AZE":
                return 31;
            case "BDI":
                return 108;
            case "BEL":
                return 56;
            case "BEN":
                return 204;
            case "BFA":
                return 854;
            case "BGD":
                return 50;
            case "BGR":
                return 100;
            case "BHR":
                return 48;
            case "BHS":
                return 44;
            case "BIH":
                return 70;
            case "BLR":
                return 112;
            case "BLZ":
                return 84;
            case "BMU":
                return 60;
            case "BOL":
                return 68;
            case "BRA":
                return 76;
            case "BRB":
                return 52;
            case "BRN":
                return 96;
            case "BTN":
                return 64;
            case "BWA":
                return 72;
            case "CAF":
                return 140;
            case "CAN":
                return 124;
            case "CCK":
                return 166;
            case "CHE":
                return 756;
            case "CHL":
                return 152;
            case "CHN":
                return 156;
            case "CIV":
                return 384;
            case "CMR":
                return 120;
            case "COD":
                return 180;
            case "COG":
                return 178;
            case "COK":
                return 184;
            case "COL":
                return 170;
            case "COM":
                return 174;
            case "CPV":
                return 132;
            case "CRI":
                return 188;
            case "CUB":
                return 192;
            case "CXR":
                return 162;
            case "CYM":
                return 136;
            case "CYP":
                return 196;
            case "CZE":
                return 203;
            case "DEU":
                return 276;
            case "DJI":
                return 262;
            case "DMA":
                return 212;
            case "DNK":
                return 208;
            case "DOM":
                return 214;
            case "DZA":
                return 12;
            case "ECU":
                return 218;
            case "EGY":
                return 818;
            case "ERI":
                return 232;
            case "ESP":
                return 724;
            case "EST":
                return 233;
            case "ETH":
                return 231;
            case "FIN":
                return 246;
            case "FJI":
                return 242;
            case "FLK":
                return 238;
            case "FRA":
                return 250;
            case "FRO":
                return 234;
            case "FSM":
                return 583;
            case "GAB":
                return 266;
            case "GBR":
                return 826;
            case "GEO":
                return 268;
            case "GHA":
                return 288;
            case "GIB":
                return 292;
            case "GIN":
                return 324;
            case "GLP":
                return 312;
            case "GMB":
                return 270;
            case "GNB":
                return 624;
            case "GNQ":
                return 226;
            case "GRC":
                return 300;
            case "GRD":
                return 308;
            case "GRL":
                return 304;
            case "GTM":
                return 320;
            case "GUF":
                return 254;
            case "GUM":
                return 316;
            case "GUY":
                return 328;
            case "HKG":
                return 344;
            case "HND":
                return 340;
            case "HRV":
                return 191;
            case "HTI":
                return 332;
            case "HUN":
                return 348;
            case "IDN":
                return 360;
            case "IND":
                return 356;
            case "IRL":
                return 372;
            case "IRN":
                return 364;
            case "IRQ":
                return 368;
            case "ISL":
                return 352;
            case "ISR":
                return 376;
            case "ITA":
                return 380;
            case "JAM":
                return 388;
            case "JOR":
                return 400;
            case "JPN":
                return 392;
            case "KAZ":
                return 398;
            case "KEN":
                return 404;
            case "KGZ":
                return 417;
            case "KHM":
                return 116;
            case "KIR":
                return 296;
            case "KNA":
                return 659;
            case "KOR":
                return 410;
            case "KWT":
                return 414;
            case "LAO":
                return 418;
            case "LBN":
                return 422;
            case "LBR":
                return 430;
            case "LBY":
                return 434;
            case "LCA":
                return 662;
            case "LIE":
                return 438;
            case "LKA":
                return 144;
            case "LSO":
                return 426;
            case "LTU":
                return 440;
            case "LUX":
                return 442;
            case "LVA":
                return 428;
            case "MAC":
                return 446;
            case "MAR":
                return 504;
            case "MCO":
                return 492;
            case "MDA":
                return 498;
            case "MDG":
                return 450;
            case "MDV":
                return 462;
            case "MEX":
                return 484;
            case "MHL":
                return 584;
            case "MLI":
                return 466;
            case "MLT":
                return 470;
            case "MMR":
                return 104;
            case "MNG":
                return 496;
            case "MNP":
                return 580;
            case "MOZ":
                return 508;
            case "MRT":
                return 478;
            case "MSR":
                return 500;
            case "MTQ":
                return 474;
            case "MUS":
                return 480;
            case "MWI":
                return 454;
            case "MYS":
                return 458;
            case "NAM":
                return 516;
            case "NCL":
                return 540;
            case "NER":
                return 562;
            case "NFK":
                return 574;
            case "NGA":
                return 566;
            case "NIC":
                return 558;
            case "NIU":
                return 570;
            case "NLD":
                return 528;
            case "NOR":
                return 578;
            case "NPL":
                return 524;
            case "NRU":
                return 520;
            case "NZL":
                return 554;
            case "OMN":
                return 512;
            case "PAK":
                return 586;
            case "PAN":
                return 591;
            case "PER":
                return 604;
            case "PHL":
                return 608;
            case "PLW":
                return 585;
            case "PNG":
                return 598;
            case "POL":
                return 616;
            case "PRI":
                return 630;
            case "PRK":
                return 408;
            case "PRT":
                return 620;
            case "PRY":
                return 600;
            case "PYF":
                return 258;
            case "QAT":
                return 634;
            case "REU":
                return 638;
            case "ROU":
                return 642;
            case "RUS":
                return 643;
            case "RWA":
                return 646;
            case "SAU":
                return 682;
            case "SDN":
                return 736;
            case "SEN":
                return 686;
            case "SGP":
                return 702;
            case "SHN":
                return 654;
            case "SLB":
                return 90;
            case "SLE":
                return 694;
            case "SLV":
                return 222;
            case "SMR":
                return 674;
            case "SOM":
                return 706;
            case "SPM":
                return 666;
            case "STP":
                return 678;
            case "SUR":
                return 740;
            case "SVK":
                return 703;
            case "SVN":
                return 705;
            case "SWE":
                return 752;
            case "SWZ":
                return 748;
            case "SYC":
                return 690;
            case "SYR":
                return 760;
            case "TCA":
                return 796;
            case "TCD":
                return 148;
            case "TGO":
                return 768;
            case "THA":
                return 764;
            case "TJK":
                return 762;
            case "TKL":
                return 772;
            case "TKM":
                return 795;
            case "TMP":
                return 626;
            case "TON":
                return 776;
            case "TTO":
                return 780;
            case "TUN":
                return 788;
            case "TUR":
                return 792;
            case "TUV":
                return 798;
            case "TWN":
                return 158;
            case "TZA":
                return 834;
            case "UGA":
                return 800;
            case "UKR":
                return 804;
            case "URY":
                return 858;
            case "USA":
                return 840;
            case "UZB":
                return 860;
            case "VAT":
                return 336;
            case "VCT":
                return 670;
            case "VEN":
                return 862;
            case "VGB":
                return 92;
            case "VIR":
                return 850;
            case "VNM":
                return 704;
            case "VUT":
                return 548;
            case "WLF":
                return 876;
            case "WSM":
                return 882;
            case "YEM":
                return 887;
            case "YUG":
                return 891;
            case "ZAF":
                return 710;
            case "ZMB":
                return 894;
            case "ZWE":
                return 716;
            default:
                return 0;
        }
    }
    public static string GetSufijo2FromSufijo3(string Sufijo3)
    {
        switch (Sufijo3)
        {
            case "AFG":
                return "AF";
            case "ALB":
                return "AL";
            case "ATA":
                return "AQ";
            case "DZA":
                return "DZ";
            case "ASM":
                return "AS";
            case "AND":
                return "AD";
            case "AGO":
                return "AO";
            case "ATG":
                return "AG";
            case "AZE":
                return "AZ";
            case "ARG":
                return "AR";
            case "AUS":
                return "AU";
            case "AUT":
                return "AT";
            case "BHS":
                return "BS";
            case "BHR":
                return "BH";
            case "BGD":
                return "BD";
            case "ARM":
                return "AM";
            case "BRB":
                return "BB";
            case "BEL":
                return "BE";
            case "BMU":
                return "BM";
            case "BTN":
                return "BT";
            case "BOL":
                return "BO";
            case "BIH":
                return "BA";
            case "BWA":
                return "BW";
            case "BRA":
                return "BR";
            case "BLZ":
                return "BZ";
            case "SLB":
                return "SB";
            case "VGB":
                return "VG";
            case "BRN":
                return "BN";
            case "BGR":
                return "BG";
            case "MMR":
                return "MM";
            case "BDI":
                return "BI";
            case "BLR":
                return "BY";
            case "KHM":
                return "KH";
            case "CMR":
                return "CM";
            case "CAN":
                return "CA";
            case "CPV":
                return "CV";
            case "CYM":
                return "KY";
            case "CAF":
                return "CF";
            case "LKA":
                return "LK";
            case "TCD":
                return "TD";
            case "CHL":
                return "CL";
            case "CHN":
                return "CN";
            case "TWN":
                return "TW";
            case "CXR":
                return "CX";
            case "CCK":
                return "CC";
            case "COL":
                return "CO";
            case "COM":
                return "KM";
            case "COG":
                return "CG";
            case "COD":
                return "CD";
            case "COK":
                return "CK";
            case "CRI":
                return "CR";
            case "HRV":
                return "HR";
            case "CUB":
                return "CU";
            case "CYP":
                return "CY";
            case "CZE":
                return "CZ";
            case "BEN":
                return "BJ";
            case "DNK":
                return "DK";
            case "DMA":
                return "DM";
            case "DOM":
                return "DO";
            case "ECU":
                return "EC";
            case "SLV":
                return "SV";
            case "GNQ":
                return "GQ";
            case "ETH":
                return "ET";
            case "ERI":
                return "ER";
            case "EST":
                return "EE";
            case "FRO":
                return "FO";
            case "FLK":
                return "FK";
            case "FJI":
                return "FJ";
            case "FIN":
                return "FI";
            case "FRA":
                return "FR";
            case "GUF":
                return "GF";
            case "PYF":
                return "PF";
            case "ATF":
                return "TF";
            case "DJI":
                return "DJ";
            case "GAB":
                return "GA";
            case "GEO":
                return "GE";
            case "GMB":
                return "GM";
            case "DEU":
                return "DE";
            case "GHA":
                return "GH";
            case "GIB":
                return "GI";
            case "KIR":
                return "KI";
            case "GRC":
                return "GR";
            case "GRL":
                return "GL";
            case "GRD":
                return "GD";
            case "GLP":
                return "GP";
            case "GUM":
                return "GU";
            case "GTM":
                return "GT";
            case "GIN":
                return "GN";
            case "GUY":
                return "GY";
            case "HTI":
                return "HT";
            case "VAT":
                return "VA";
            case "HND":
                return "HN";
            case "HKG":
                return "HK";
            case "HUN":
                return "HU";
            case "ISL":
                return "IS";
            case "IND":
                return "IN";
            case "IDN":
                return "ID";
            case "IRN":
                return "IR";
            case "IRQ":
                return "IQ";
            case "IRL":
                return "IE";
            case "ISR":
                return "IL";
            case "ITA":
                return "IT";
            case "CIV":
                return "CI";
            case "JAM":
                return "JM";
            case "JPN":
                return "JP";
            case "KAZ":
                return "KZ";
            case "JOR":
                return "JO";
            case "KEN":
                return "KE";
            case "PRK":
                return "KP";
            case "KOR":
                return "KR";
            case "KWT":
                return "KW";
            case "KGZ":
                return "KG";
            case "LAO":
                return "LA";
            case "LBN":
                return "LB";
            case "LSO":
                return "LS";
            case "LVA":
                return "LV";
            case "LBR":
                return "LR";
            case "LBY":
                return "LY";
            case "LIE":
                return "LI";
            case "LTU":
                return "LT";
            case "LUX":
                return "LU";
            case "MAC":
                return "MO";
            case "MDG":
                return "MG";
            case "MWI":
                return "MW";
            case "MYS":
                return "MY";
            case "MDV":
                return "MV";
            case "MLI":
                return "ML";
            case "MLT":
                return "MT";
            case "MTQ":
                return "MQ";
            case "MRT":
                return "MR";
            case "MUS":
                return "MU";
            case "MEX":
                return "MX";
            case "MCO":
                return "MC";
            case "MNG":
                return "MN";
            case "MDA":
                return "MD";
            case "MSR":
                return "MS";
            case "MAR":
                return "MA";
            case "MOZ":
                return "MZ";
            case "OMN":
                return "OM";
            case "NAM":
                return "NA";
            case "NRU":
                return "NR";
            case "NPL":
                return "NP";
            case "NLD":
                return "NL";
            case "ANT":
                return "AN";
            case "ABW":
                return "AW";
            case "NCL":
                return "NC";
            case "VUT":
                return "VU";
            case "NZL":
                return "NZ";
            case "NIC":
                return "NI";
            case "NER":
                return "NE";
            case "NGA":
                return "NG";
            case "NIU":
                return "NU";
            case "NFK":
                return "NF";
            case "NOR":
                return "NO";
            case "MNP":
                return "MP";
            case "FSM":
                return "FM";
            case "MHL":
                return "MH";
            case "PLW":
                return "PW";
            case "PAK":
                return "PK";
            case "PAN":
                return "PA";
            case "PNG":
                return "PG";
            case "PRY":
                return "PY";
            case "PER":
                return "PE";
            case "PHL":
                return "PH";
            case "POL":
                return "PL";
            case "PRT":
                return "PT";
            case "GNB":
                return "GW";
            case "TMP":
                return "TP";
            case "PRI":
                return "PR";
            case "QAT":
                return "QA";
            case "REU":
                return "RE";
            case "ROU":
                return "RO";
            case "RUS":
                return "RU";
            case "RWA":
                return "RW";
            case "SHN":
                return "SH";
            case "KNA":
                return "KN";
            case "AIA":
                return "AI";
            case "LCA":
                return "LC";
            case "SPM":
                return "PM";
            case "VCT":
                return "VC";
            case "SMR":
                return "SM";
            case "STP":
                return "ST";
            case "SAU":
                return "SA";
            case "SEN":
                return "SN";
            case "SYC":
                return "SC";
            case "SLE":
                return "SL";
            case "SGP":
                return "SG";
            case "SVK":
                return "SK";
            case "VNM":
                return "VN";
            case "SVN":
                return "SI";
            case "SOM":
                return "SO";
            case "ZAF":
                return "ZA";
            case "ZWE":
                return "ZW";
            case "ESP":
                return "ES";
            case "SDN":
                return "SD";
            case "SUR":
                return "SR";
            case "SWZ":
                return "SZ";
            case "SWE":
                return "SE";
            case "CHE":
                return "CH";
            case "SYR":
                return "SY";
            case "TJK":
                return "TJ";
            case "THA":
                return "TH";
            case "TGO":
                return "TG";
            case "TKL":
                return "TK";
            case "TON":
                return "TO";
            case "TTO":
                return "TT";
            case "ARE":
                return "AE";
            case "TUN":
                return "TN";
            case "TUR":
                return "TR";
            case "TKM":
                return "TM";
            case "TCA":
                return "TC";
            case "TUV":
                return "TV";
            case "UGA":
                return "UG";
            case "UKR":
                return "UA";
            case "MKD":
                return "MK";
            case "EGY":
                return "EG";
            case "GBR":
                return "GB";
            case "TZA":
                return "TZ";
            case "USA":
                return "US";
            case "VIR":
                return "VI";
            case "BFA":
                return "BF";
            case "URY":
                return "UY";
            case "UZB":
                return "UZ";
            case "VEN":
                return "VE";
            case "WLF":
                return "WF";
            case "WSM":
                return "WS";
            case "YEM":
                return "YE";
            case "YUG":
                return "YU";
            case "ZMB":
                return "ZM";
            default:
                return "ERROR!";
        }
    }
    public static string GetSufijo3FromName(string Name)
    {
        switch (Name.ToUpper())
        {
            case "AFGHANISTAN":
                return "AFG";
            case "ALBANIA":
                return "ALB";
            case "ANTARCTICA":
                return "ATA";
            case "ALGERIA":
                return "DZA";
            case "AMERICAN SAMOA":
                return "ASM";
            case "ANDORRA":
                return "AND";
            case "ANGOLA":
                return "AGO";
            case "ANTIGUA AND BARBUDA":
                return "ATG";
            case "AZERBAIJAN":
                return "AZE";
            case "ARGENTINA":
                return "ARG";
            case "AUSTRALIA":
                return "AUS";
            case "AUSTRIA":
                return "AUT";
            case "BAHAMAS":
                return "BHS";
            case "BAHRAIN":
                return "BHR";
            case "BANGLADESH":
                return "BGD";
            case "ARMENIA":
                return "ARM";
            case "BARBADOS":
                return "BRB";
            case "BELGIUM":
                return "BEL";
            case "BERMUDA":
                return "BMU";
            case "BHUTAN":
                return "BTN";
            case "BOLIVIA":
                return "BOL";
            case "BOSNIA HERCEGOVINA":
                return "BIH";
            case "BOTSWANA":
                return "BWA";
            case "BRAZIL":
                return "BRA";
            case "BELIZE":
                return "BLZ";
            case "SOLOMON ISLANDS":
                return "SLB";
            case "VIRGIN ISLANDS (BRITISH)":
                return "VGB";
            case "BRUNEI DARUSSALAM":
                return "BRN";
            case "BULGARIA":
                return "BGR";
            case "MYANMAR":
                return "MMR";
            case "BURUNDI":
                return "BDI";
            case "BYELORUSSIAN SSR":
                return "BLR";
            case "CAMBODIA":
                return "KHM";
            case "CAMEROON":
                return "CMR";
            case "CANADA":
                return "CAN";
            case "CAPE VERDE":
                return "CPV";
            case "CAYMAN ISLANDS":
                return "CYM";
            case "CENTRAL AFRICAN REPUBLIC":
                return "CAF";
            case "SRI LANKA":
                return "LKA";
            case "CHAD":
                return "TCD";
            case "CHILE":
                return "CHL";
            case "CHINA":
                return "CHN";
            case "TAIWAN, PROVINCE OF CHINA":
                return "TWN";
            case "CHRISTMAS ISLAND":
                return "CXR";
            case "COCOS (KEELING) ISLANDS":
                return "CCK";
            case "COLOMBIA":
                return "COL";
            case "COMOROS":
                return "COM";
            case "CONGO":
                return "COG";
            case "Rep blica Democr tica del Congo":
                return "COD";
            case "COOK ISLANDS":
                return "COK";
            case "COSTA RICA":
                return "CRI";
            case "CROATIA":
                return "HRV";
            case "CUBA":
                return "CUB";
            case "CYPRUS":
                return "CYP";
            case "CZECH REPUBLIC":
                return "CZE";
            case "BENIN":
                return "BEN";
            case "DENMARK":
                return "DNK";
            case "DOMINICA":
                return "DMA";
            case "DOMINICAN REPUBLIC":
                return "DOM";
            case "ECUADOR":
                return "ECU";
            case "EL SALVADOR":
                return "SLV";
            case "EQUATORIAL GUINEA":
                return "GNQ";
            case "ETHIOPIA":
                return "ETH";
            case "ERITREA":
                return "ERI";
            case "ESTONIA":
                return "EST";
            case "FAROE ISLANDS":
                return "FRO";
            case "FALKLAND ISLANDS (MALVINAS)":
                return "FLK";
            case "FIJI":
                return "FJI";
            case "FINLAND":
                return "FIN";
            case "FRANCE":
                return "FRA";
            case "FRENCH GUIANA":
                return "GUF";
            case "FRENCH POLYNESIA":
                return "PYF";
            case "FRENCH SOUTHERN TERRITORIES":
                return "ATF";
            case "DJIBOUTI":
                return "DJI";
            case "GABON":
                return "GAB";
            case "GEORGIA":
                return "GEO";
            case "GAMBIA":
                return "GMB";
            case "GERMANY":
                return "DEU";
            case "GHANA":
                return "GHA";
            case "GIBRALTAR":
                return "GIB";
            case "KIRIBATI":
                return "KIR";
            case "GREECE":
                return "GRC";
            case "GREENLAND":
                return "GRL";
            case "GRENADA":
                return "GRD";
            case "GUADELOUPE":
                return "GLP";
            case "GUAM":
                return "GUM";
            case "GUATEMALA":
                return "GTM";
            case "GUINEA":
                return "GIN";
            case "GUYANA":
                return "GUY";
            case "HAITI":
                return "HTI";
            case "VATICAN CITY STATE (HOLY SEE)":
                return "VAT";
            case "HONDURAS":
                return "HND";
            case "HONG KONG":
                return "HKG";
            case "HUNGARY":
                return "HUN";
            case "ICELAND":
                return "ISL";
            case "INDIA":
                return "IND";
            case "INDONESIA":
                return "IDN";
            case "IRAN (ISLAMIC REPUBLIC OF)":
                return "IRN";
            case "IRAQ":
                return "IRQ";
            case "IRELAND":
                return "IRL";
            case "ISRAEL":
                return "ISR";
            case "ITALY":
                return "ITA";
            case "COTE D\'IVOIRE":
                return "CIV";
            case "JAMAICA":
                return "JAM";
            case "JAPAN":
                return "JPN";
            case "KAZAKHSTAN":
                return "KAZ";
            case "JORDAN":
                return "JOR";
            case "KENYA":
                return "KEN";
            case "KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF":
                return "PRK";
            case "KOREA, REPUBLIC OF":
                return "KOR";
            case "KUWAIT":
                return "KWT";
            case "KYRGYZSTAN":
                return "KGZ";
            case "LAO PEOPLE\'S DEMOCRATIC REPUBLIC":
                return "LAO";
            case "LEBANON":
                return "LBN";
            case "LESOTHO":
                return "LSO";
            case "LATVIA":
                return "LVA";
            case "LIBERIA":
                return "LBR";
            case "LIBYAN ARAB JAMAHIRIYA":
                return "LBY";
            case "LIECHTENSTEIN":
                return "LIE";
            case "LITHUANIA":
                return "LTU";
            case "LUXEMBOURG":
                return "LUX";
            case "MACAU":
                return "MAC";
            case "MADAGASCAR":
                return "MDG";
            case "MALAWI":
                return "MWI";
            case "MALAYSIA":
                return "MYS";
            case "MALDIVES":
                return "MDV";
            case "MALI":
                return "MLI";
            case "MALTA":
                return "MLT";
            case "MARTINIQUE":
                return "MTQ";
            case "MAURITANIA":
                return "MRT";
            case "MAURITIUS":
                return "MUS";
            case "MEXICO":
                return "MEX";
            case "MONACO":
                return "MCO";
            case "MONGOLIA":
                return "MNG";
            case "MOLDOVA, REPUBLIC OF":
                return "MDA";
            case "MONTSERRAT":
                return "MSR";
            case "MOROCCO":
                return "MAR";
            case "MOZAMBIQUE":
                return "MOZ";
            case "OMAN":
                return "OMN";
            case "NAMIBIA":
                return "NAM";
            case "NAURU":
                return "NRU";
            case "NEPAL":
                return "NPL";
            case "NETHERLANDS":
                return "NLD";
            case "NETHERLANDS ANTILLES":
                return "ANT";
            case "ARUBA":
                return "ABW";
            case "NEW CALEDONIA":
                return "NCL";
            case "VANUATU":
                return "VUT";
            case "NEW ZEALAND":
                return "NZL";
            case "NICARAGUA":
                return "NIC";
            case "NIGER":
                return "NER";
            case "NIGERIA":
                return "NGA";
            case "NIUE":
                return "NIU";
            case "NORFOLK ISLAND":
                return "NFK";
            case "NORWAY":
                return "NOR";
            case "NORTHERN MARIANA ISLANDS":
                return "MNP";
            case "MICRONESIA":
                return "FSM";
            case "MARSHALL ISLANDS":
                return "MHL";
            case "PALAU":
                return "PLW";
            case "PAKISTAN":
                return "PAK";
            case "PANAMA":
                return "PAN";
            case "PAPUA NEW GUINEA":
                return "PNG";
            case "PARAGUAY":
                return "PRY";
            case "PERU":
                return "PER";
            case "PHILIPPINES":
                return "PHL";
            case "POLAND":
                return "POL";
            case "PORTUGAL":
                return "PRT";
            case "GUINEA-BISSAU":
                return "GNB";
            case "EAST TIMOR":
                return "TMP";
            case "PUERTO RICO":
                return "PRI";
            case "QATAR":
                return "QAT";
            case "REUNION":
                return "REU";
            case "ROMANIA":
                return "ROU";
            case "RUSSIAN FEDERATION":
                return "RUS";
            case "RWANDA":
                return "RWA";
            case "ST. HELENA":
                return "SHN";
            case "SAINT KITTS AND NEVIS":
                return "KNA";
            case "ANGUILLA":
                return "AIA";
            case "SAINT LUCIA":
                return "LCA";
            case "ST. PIERRE AND MIQUELON":
                return "SPM";
            case "SAINT VINCENT AND THE GRENADINES":
                return "VCT";
            case "SAN MARINO":
                return "SMR";
            case "SAO TOME AND PRINCIPE":
                return "STP";
            case "SAUDI ARABIA":
                return "SAU";
            case "SENEGAL":
                return "SEN";
            case "SEYCHELLES":
                return "SYC";
            case "SIERRA LEONE":
                return "SLE";
            case "SINGAPORE":
                return "SGP";
            case "ESLOVAQUIA":
                return "SVK";
            case "VIET NAM":
                return "VNM";
            case "SLOVENIA":
                return "SVN";
            case "SOMALIA":
                return "SOM";
            case "SOUTH AFRICA":
                return "ZAF";
            case "ZIMBABWE":
                return "ZWE";
            case "SPAIN":
                return "ESP";
            case "SUDAN":
                return "SDN";
            case "SURINAME":
                return "SUR";
            case "SWAZILAND":
                return "SWZ";
            case "SWEDEN":
                return "SWE";
            case "SWITZERLAND":
                return "CHE";
            case "SYRIAN ARAB REPUBLIC":
                return "SYR";
            case "TAJIKISTAN":
                return "TJK";
            case "THAILAND":
                return "THA";
            case "TOGO":
                return "TGO";
            case "TOKELAU":
                return "TKL";
            case "TONGA":
                return "TON";
            case "TRINIDAD AND TOBAGO":
                return "TTO";
            case "UNITED ARAB EMIRATES":
                return "ARE";
            case "TUNISIA":
                return "TUN";
            case "TURKEY":
                return "TUR";
            case "TURKMENISTAN":
                return "TKM";
            case "TURKS AND CAICOS ISLANDS":
                return "TCA";
            case "TUVALU":
                return "TUV";
            case "UGANDA":
                return "UGA";
            case "UKRAINIAN SSR":
                return "UKR";
            case "EGYPT":
                return "EGY";
            case "UNITED KINGDOM":
                return "GBR";
            case "TANZANIA, UNITED REPUBLIC OF":
                return "TZA";
            case "UNITED STATES":
                return "USA";
            case "UNITEDSTATES":
                return "USA";
            case "VIRGIN ISLANDS (U.S.)":
                return "VIR";
            case "BURKINA FASO":
                return "BFA";
            case "URUGUAY":
                return "URY";
            case "UZBEKISTAN":
                return "UZB";
            case "VENEZUELA":
                return "VEN";
            case "WALLIS AND FUTUNA ISLANDS":
                return "WLF";
            case "SAMOA":
                return "WSM";
            case "YEMEN, REPUBLIC OF":
                return "YEM";
            case "YUGOSLAVIA":
                return "YUG";
            case "ZAMBIA":
                return "ZMB";
            case "USSR":
                return "SU";
            case "BRITISH INDIAN OCEAN TERRITORY":
                return "IO";
            case "BOUVET ISLAND":
                return "BV";
            case "HEARD AND MC DONALD ISLANDS":
                return "HM";
            case "SVALBARD AND JAN MAYEN ISLANDS":
                return "SJ";
            case "NEUTRAL ZONE":
                return "NT";
            case "UNITED STATES MINOR OUTLYING ISLANDS":
                return "UM";
            case "PITCAIRN":
                return "PN";
            case "ZAIRE":
                return "ZR";
            case "WESTERN SAHARA":
                return "EH";
            case "CZECHOSLOVAKIA":
                return "CS";
            default:
                return "ERROR!";
        }
    }
}